apiVersion: v1
description: BuildBuddy Open Source
name: buildbuddy
version: 0.0.32 # Chart version
appVersion: 2.1.0 # Version of deployed app
keywords:
  - buildbuddy
  - bazel
  - build
  - test
  - remote-cache
  - rbe
home: https://buildbuddy.io
icon: https://uploads-ssl.webflow.com/5eeba6a68ba54530ffd09006/5eeba8935be5c67625f86a3a_buildbuddy.svg
source:
  - https://github.com/buildbuddy-io/buildbuddy
  - https://github.com/buildbuddy-io/buildbuddy-helm
maintainers:
  - name: siggisim
    email: siggi@buildbuddy.io
  - name: tylerwilliams
    email: tyler@buildbuddy.io
