apiVersion: v1
description: BuildBuddy Redis LRU
name: buildbuddy-redis
version: 0.0.4 # Chart version
appVersion: 5.0.4 # Version of deployed app
keywords:
  - buildbuddy
  - bazel
  - build
  - test
  - remote-cache
  - rbe
  - lru
home: https://buildbuddy.io
icon: https://uploads-ssl.webflow.com/5eeba6a68ba54530ffd09006/5eeba8935be5c67625f86a3a_buildbuddy.svg
source:
  - https://github.com/redis/redis
  - https://github.com/buildbuddy-io/buildbuddy-helm
maintainers:
  - name: siggisim
    email: siggi@buildbuddy.io
  - name: tylerwilliams
    email: tyler@buildbuddy.io
